name: Docker Image buildx by tag on alpine

on:
  push:
    tags:
      - '*' # Push events to matching *, i.e. 1.0.0 v1.0, v20.15.10

permissions:
  contents: write
  discussions: write

env:
  # name of docker image
  DOCKER_HUB_USER: sinlov
  IMAGE_BUILD_OS_NAME: buster
  IMAGE_NAME: docker-rust-buster
  DOCKER_IMAGE_PLATFORMS: linux/amd64,linux/386,linux/arm64/v8,linux/arm/v7

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        docker_image:
          - platform: linux/amd64
          - platform: linux/386
          - platform: linux/arm64/v8
          - platform: linux/arm/v7
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: "Login into registry as user: env.DOCKER_HUB_USER"
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push
      uses: docker/build-push-action@v4 # https://github.com/docker/build-push-action
      with:
        context: .
        file: Dockerfile
        platforms: ${{ matrix.docker_image.platform }}
        tags: ${{ env.DOCKER_HUB_USER }}/${{ env.IMAGE_NAME }}:latest-{{ env.IMAGE_BUILD_OS_NAME }}
        no-cache: false
        push: true

    - uses: softprops/action-gh-release@master # https://github.com/softprops/action-gh-release#-customizing
      name: pre release
      if: startsWith(github.ref, 'refs/tags/')
      with:
        ## with permissions to create releases in the other repo
        token: "${{ secrets.GITHUB_TOKEN }}"
#        body_path: ${{ github.workspace }}-CHANGELOG.txt
        prerelease: true
